### ISSUE TITLE
giving annoying narration audio on some channels   

### ISSUE THREAD

**Issue by hafez123** [kodi-pvr/pvr.vuplus#48] opened 2016-12-26 21:21 UTC
I know channels gets  transmitted with two three different audio scripts. lot of the channels get impaired audio description (narration) when transcoding, need option to change this. or some kind of script that i can disable narration on all channels.

**Comment by phunkyfish** [comment] 2018-10-04 15:16
@hafez123 Can you supply steps to reproduce?

**Comment by phunkyfish** [comment] 2018-10-19 23:58
@hafez123 I will close this issue at the end of the month unless you respond in the meantime to keep it open.

**Comment by phunkyfish** [comment] 2018-10-30 19:51
Closing due to inactivity

**Closed by phunkyfish** 2018-10-30 19:51 UTC
Labels: enhancement
