### ISSUE TITLE
buffering issues on some channels osmc live tv

### ISSUE THREAD

**Issue by eboelens** [kodi-pvr/pvr.vuplus#436] opened 2023-08-13 09:07 UTC
Hi
rpi4 8mb
osmc latest
enigma2 vuplus solo4k openpli8.3
since a few weeks I have a lot buffering issues on some channels only with live tv.
log= https://paste.osmc.tv/lecoseguha
any idea please

**Comment by phunkyfish** [comment] 2023-08-13 09:37
What version of Kodi is this based on? Same for the addon and OpenWebIf. What changed in the last few weeks.

it’s hard to read your log as it’s not a format I’m used to.

**Comment by eboelens** [comment] 2023-08-13 10:33
Osmc running kodi 20.2
I will try another format
Nothing changed i think
If it is too difficult i will reinstall everything

Erik

Op zondag 13 augustus 2023 schreef phunkyfish ***@***.***>:

**Comment by phunkyfish** [comment] 2023-08-13 17:59
Could it be OpenPli 8.3? You say you’ve been running it for a few weeks.

**Comment by eboelens** [comment] 2023-08-16 17:28
i prepared a new sdcard and the problem is still there.
Buffering and soundproblems when changing channels

**Comment by eboelens** [comment] 2023-08-16 17:29
so maybe openpli ?

**Comment by eboelens** [comment] 2023-08-16 20:32
I tried openpli 7.3 but I get the same problem
so:
new osmc on rpi4 8mb
and openpli 7.3 gives me the same problems

**Comment by phunkyfish** [comment] 2023-08-16 21:09
Did this ever work correctly? If so how long ago?

**Comment by eboelens** [comment] 2023-08-17 11:38
sorry difficult to say I think a good month

below extra feedback to osmc community
I took some time yesterday :
reinstalled osmc but problems remain
then set openpli to 7.3 but problems remain
then downgraded osmc to version 2023.05-1 and it works :slight_smile:

i now go back to openpli 8.3
it works
now I do all the updates from openpli 8.3
it works
I try now 2023.06-1 osmc
it does not work !!
what strikes me now during the installation, manually with balenaetcher, at the first boot there is always one :frowning: and automatically it will be fine again
i tried a new osmc installation and wait for the first boot
whith  first boot, when I select my language Dutch it goes to :frowning: then after a few seconds osmc is running
still buffering problems and sound
pffff
sorry but I tried libreelec and it works !!
I hope to return to OSMC as soon as possible

**Comment by phunkyfish** [comment] 2023-08-17 13:14
Ok, then I think the issue is definitely with OSMC. I’ll close the issue for now.

**Closed as not planned by phunkyfish** 2023-08-17 13:14 UTC

**Comment by samnazarko** [comment] 2023-08-17 15:01
Please see https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/ so we (OSMC) can get this solved for you promptly.
