### ISSUE TITLE
Kodi causes many open files in VuPlus Duo2

### ISSUE THREAD

**Issue by JojoS62** [kodi-pvr/pvr.vuplus#293] opened 2020-07-25 12:51 UTC
Problem:
I have a VUPlus box and two clients, a pc and a libreelec on a PI4. The box runs out of resources (>1356 open files) after about 1-2 days. The open files are many many /dev/input/event0. When this happens, the enigma2 process is not responding and streaming stops until the box is rebooted. The linux kernel in the box is still responsive, accessing with a ssh terminal is no problem.
I found that the Kodi on the Pi4 is causing this problem when it is running, the open files on the vuplus is increasing constantly.
Then I started Wireshark and I can see that the movielist ist polled frequently. The settings is every 2 minutes (default). Now I increased to 240 min and the no. of open files in the box is stable for some time now.
There are many file on the hdd, the xml movielist has a size of >430 kB, the time from request to response is about 4.5 s and there are other requests in parallel, e.g. the webtime query that may take also 4.5 s.
Even the movielist is large, it should not cause many open files in the box. I don't know which partner causes the trouble, it may be the combination. Before, I had Kodi running on a Pi3 and this happened also. With Kodi on the PC, I didn't notice such problems.
The vuplus/Enigma2 plugin is the current version 3.28.9.1, the Vuplus Image is also up to date.

**Comment by phunkyfish** [comment] 2020-07-25 14:04
Do you think that the PI4 is not closing the open files correctly? Or that the issue is on the Enigma2 device?

Can you show a listing of the open files?

**Comment by JojoS62** [comment] 2020-07-25 14:25
Thanks for your fast reply. I have no clue what is causing the problem. The box without Kodi access runs without problems for month, now with the RPi Kodi client it causes the crash after 1-2 days. So, there must be some relation.
I can send also the Wireshark capture if it helps.
Is there some timeout for requesting the movielist / time or other information from the box?
And the many /dev/input/event files are strange, as far as I understand this is the IR receiver.

[lsof.txt](https://github.com/kodi-pvr/pvr.vuplus/files/4975697/lsof.txt)

**Comment by phunkyfish** [comment] 2020-07-25 14:47
I’m not sure I’d know what to do with a wire shark 😉

There is no timeout. Let me try plugging in a Rpi here and see if I can make it happen.

**Comment by JojoS62** [comment] 2020-07-27 14:03
After reducing the query intervall for the recordings, the number of open files is growing much slower. I think also this more a problem on the vuplus box, I will try to get more info from this side.
And I have activated the logging on the Kodi at the PC. There I see errors after the query for web/signal, the box answers with no values. But I think this not a big issue and not my major problem.
A query for /web/tunerstatus in the webbrowser gives the same result.

```
2020-07-27 12:32:28.832 T:22748   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::GetTunerSignal Could not parse e2ber from result!
2020-07-27 12:32:28.832 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Tuner Details - name: Deaktiviert, status: Deaktiviert
2020-07-27 12:32:28.832 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Service Details - service: n-tv HD, provider: CBC
2020-07-27 12:32:28.832 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Signal - snrPercent: 0, ber: 0, signal strength: 0
2020-07-27 12:32:29.333 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Enigma2::GetTunerSignal - Calling backend for Signal Status after interval of 10 seconds
2020-07-27 12:32:29.364 T:22748   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::GetTunerSignal Could not parse e2ber from result!
2020-07-27 12:32:29.364 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Tuner Details - name: Deaktiviert, status: Deaktiviert
2020-07-27 12:32:29.364 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Service Details - service: n-tv HD, provider: CBC
2020-07-27 12:32:29.364 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Signal - snrPercent: 0, ber: 0, signal strength: 0
2020-07-27 12:32:29.865 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Enigma2::GetTunerSignal - Calling backend for Signal Status after interval of 10 seconds
2020-07-27 12:32:29.895 T:22748   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::GetTunerSignal Could not parse e2ber from result!
2020-07-27 12:32:29.895 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Tuner Details - name: Deaktiviert, status: Deaktiviert
2020-07-27 12:32:29.895 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Service Details - service: n-tv HD, provider: CBC
2020-07-27 12:32:29.895 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Signal - snrPercent: 0, ber: 0, signal strength: 0
2020-07-27 12:32:30.396 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - Enigma2::GetTunerSignal - Calling backend for Signal Status after interval of 10 seconds
2020-07-27 12:32:30.425 T:22748   ERROR: AddOnLog: Enigma2 Client: pvr.vuplus - enigma2::Admin::GetTunerSignal Could not parse e2ber from result!
2020-07-27 12:32:30.425 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Tuner Details - name: Deaktiviert, status: Deaktiviert
2020-07-27 12:32:30.425 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Service Details - service: n-tv HD, provider: CBC
2020-07-27 12:32:30.425 T:22748  NOTICE: AddOnLog: Enigma2 Client: pvr.vuplus - SignalStatus Signal - snrPercent: 0, ber: 0, signal strength: 0
```

![grafik](https://user-images.githubusercontent.com/6775562/88550705-439c3e80-d022-11ea-8391-f53ab37672b1.png)

**Comment by phunkyfish** [comment] 2020-07-27 14:25
If it’s the vuplus box then it’s either OpenWebIf or Enigma2 itself that causes this. 

Maybe start by opening an issue on OpenWebIf.

**Comment by JojoS62** [comment] 2020-07-27 14:59
found some reason: /web/signal or /web/tunersignal queries the signal for the active tv program in the box. When the box is off, the Kodi plugin gets this empty result, when the the box is on the result is valid for that signal.

> Maybe start by opening an issue on OpenWebIf.

you did already :)
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/854

E2OpenPlugins is a repo for the plugins, is there also a github repo for the Enigma2 software itself?

**Comment by phunkyfish** [comment] 2020-07-27 15:09
What I meant was raise an issue with OpenWebIf about the ever growing number of open files when using a Rpi.

If the maintainer there doesn't think the problem is openwebif he might steer us to the right project. E2 is made up of many many projects.

**Comment by JojoS62** [comment] 2020-07-27 15:18
ok, thanks, I understand and will try.

**Closed as completed** 2020-09-22 10:29 UTC
