### ISSUE TITLE
Backend channel numbers changed but do not match STB

### ISSUE THREAD

**Issue by M2k80** [kodi-pvr/pvr.vuplus#220] opened 2019-05-06 18:24 UTC
hello,
some time ago, all my bouquets had sorted channel numbers, 1,2,3,4,5, but since some weeks this changed to 1,3,7,9,13 etc...
every bouquet began with 1,2,3,4 and now the channel numbers are taken from "all channels" and all bouquets are disorderd.
i liked it how it was before. why was this be changed.

**Comment by phunkyfish** [comment] 2019-05-06 19:37
Use channel numbers from backend was implemented. Just disable that in pvr settings and clear the cache and you should be back to normal.

**Comment by M2k80** [comment] 2019-05-06 20:00
it is already disabled (default option). i enabled it now and now the bouguets are looking good, but when i open now all channels, i have 4 x channel 1, 4 x channel 2 etc..
before these changes to the pvr the category "all channels" was numbered 1,2,3,4 etc same like the bouquets.

i just compared my channel numbers on my vu+ - none of both new options in the pvr settings match my channel numbers on the vu+.
i will make some screenshots now

**Comment by M2k80** [comment] 2019-05-06 20:14
my channle list from VU+
![VU Channellist](https://user-images.githubusercontent.com/6137556/57252390-42ad7480-704c-11e9-8b92-e2cc48d105eb.jpg)

all default, backend channel number off - all channels are numbered 1,2,3,4,etc - bouquets are numbered like 3,8,12,16
![IMAG1277](https://user-images.githubusercontent.com/6137556/57252170-d7fc3900-704b-11e9-8e60-4fd31376c1a4.jpg)

backend channel numbers on - all channels are looking like 1,1,1,1,2,2,2,2,3,3,3,3 - bouquets are 1,2,3,4,5
![All channels with backend channelnumbers enabled](https://user-images.githubusercontent.com/6137556/57252420-5062fa00-704c-11e9-86d5-437c40425558.jpg)

**Comment by phunkyfish** [comment] 2019-05-06 20:36
Do you use AutoBouquetMaker to create your bouquets?

When you disable use channels from backend and clear the pvr cache is the behaviour the same as before? Because it should be.

Also what version of the addon are you running?

**Comment by phunkyfish** [comment] 2019-05-06 20:40
With the option disabled each channel will get the next available channel number as it is read. If a channel is in multiple bouquets it will keep the channel number from the first time it is read. Behaviour has been like this for at least a year now on Leia.

**Comment by M2k80** [comment] 2019-05-06 21:09
my bouquets are handmade with e-channelizer, i use them for 1 year now.
i cleared the data every time i changed, like you said above.
if i change back to the default option and clear pvr cache, its like before.
both options get different results, but both dont look good.
my version of the addon is 4.2.0, problem was same on 4.1.0 and older... idk when it started.
i have to 2 kodi devices and both have this problem for now.
something has changed in the last 4 weeks or maybe 8 weeks. all channels was ever listed with 1,2,3,4,5 same like the bouquets, all bouquet i choosed was listed with 1,2,3,4

i would not came here if all were the same like ever.
i never used the channel numbers from the backend, and kodi set the numbers always 1,2,3,4 for all bouquets, but not it does not anymore. I never changed numbering its always the default option on pvr also in the addon.

look at the screenshots, i described all pictures.
with the option use channel numbers from backend enabled i get 1,1,1,1 for all channels, this cant be correct? backend is the vu+ right? but here kodi generates new channel numbers for every bouquet, i have 4 bouquets, so in "all channels" there is every channel 1 from every bouquet set to channel 1.
you see my backend channel numbers from my vu+ screenshot, this is completly different what kodi shows. if i enable backend channel nummbers my sky hd bouquet should have 68,69,70 etc. this would be correct.
my bouquets in kodi should show 1,2,3,4 etc if backend numbers are disabled and not enabled.

my english is not so well, that i could explain it better.
i give up.
if you think this is all correct, close this issue.

ps. i saw in kodi forums poeple are complaining too about wrong channel numbers, so i am just not the only one

**Comment by phunkyfish** [comment] 2019-05-06 21:23
Can you pastebin the output of:

http://<your-ip>/web/getservices

They provide the names of some sample bouquets that are incorrect?

**Comment by phunkyfish** [comment] 2019-05-06 21:41
The backend channel numbers come from OpenWebIf. What version of OpenWebIf do you use? They will only work with OpenWebIf 1.3.5 or later.

Can you also post a debug log?

**Comment by M2k80** [comment] 2019-05-07 03:44
i am using latest openvix.
http:///web/getservices there are my bouquets..no samples
https://paste.kodi.tv/ujiqecofiq

if using backend channels, bouquets are numbered like 1,2,3,4 - this sorting is fine for me, but they are not my backend numbers. but here the group "all channels" is generated by kodi and you have every channel number 4 times - this seems wrong to me, and in the past it was generated with 1,2,3,4 channel numbering. "all channels" is useless if using backend channel nummbers, explained on the last screenshot

**Comment by phunkyfish** [comment] 2019-05-07 07:21
Can you check your OpenWebIf version? As I’m using a manually installed OpenWebIf I don’t know what the latest on OpenVix should be.

This url will provide it:

```
http://<your-ip>/web/deviceinfo
```

To verify what is happening we need to check a get services api call. So assuming you are running OpenWebIf 1.3.5 or higher you want to check a URL like this:

```
http://<your-ip>/api/getservices?provider=1&picon=1&sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2EZiggo%2Etv%22%20ORDER%20BY%20bouquet
```

However you need to replace the sRef value with the url encoded value from a bouquet in the previous getservices call you posted.

Is this making sense? Once you can pastebin that output we can start to capture logs to figure out what is happening.

If this is happening for you then it’s happening for someone else so best to get to the bottom of it.

One other important question, do you have a master bouquet, I.e. one bouquet containing all the channels?

**Comment by M2k80** [comment] 2019-05-07 15:39
my webif is 1.3.6
your link show me this:
{
 "services": [], 
 "pos": 0
}
are you sure it is correct? i dont have ziggo or etv.
(i could get a working url with my bouquet, its sorted with 1,2,3,4,5 etc)

as i said last night:
> if using backend channels, bouquets are numbered like 1,2,3,4 - this sorting is fine for me,

but the category "all channels" is generated by kodi, so if every channel in my bouquets begin with No1 - in "all channels" i get 4x No1 - shouldnt get "all channels its own numbering? because in this case "all channels is getting useless

----
maybe we shoult start this from the beginning....some things are cleared up for me now and some not.

**Comment by phunkyfish** [comment] 2019-05-07 15:43
Ok, so the fact your are getting 1,2,3,4 when using backend channel numbers is wrong.

Let me send you a url with one of your bouquets. The one I gave you was a sample.

Gimme a few mins.

**Comment by M2k80** [comment] 2019-05-07 15:44
https://paste.kodi.tv/fufupudifa i think this is what you want to see...

this is the point why i said this
> maybe we shoult start this from the beginning....some things are cleared up for me now and some not.

i have understand that all my bouquets begin with 1,2,3,4 in kodi - its the same what getservices shows.
now the point i dont understand -> my vu show in channel view complete different numbers - so thats a thing you cant do anything about that, because openvix does its numbering on its own.

as i said, i am fine if every bouquet in kodi begin with 1,2,3,4. - one of these things that are clear now :)
the one i dont understand is "all channels" - take a look at my last screenshot

**Comment by phunkyfish** [comment] 2019-05-07 16:20
That is exactly what I want to see.  So the numbers are incorrect, the "pos" should match what you see on your STB. These numbers should be unique across bouquets.

Do you have the same channels in multiple bouquets or each channel only exists in one bouquet?

The reasons "all channels" has the same numbers repeated is because the channel numbers are set by the bouquets. But OpenWebIf is not returning the right bouquet numbers so it looks wrong.

In my setup each bouquet sets the channel number and they are exactly the numbers I see in all channels.

**Comment by phunkyfish** [comment] 2019-05-07 16:23
I think if you use ABM it will work correctly, what e-channelizer does is not compatible with how OpenWebIf does the channel numbers (no idea why this is).

You should be able to do the same thing with ABM.

**Comment by M2k80** [comment] 2019-05-07 16:25
i can show you the text in the bouquet files?
couldnt it a webif problem?
where did you get your newer webif version? maybe i should try this one?

**Comment by M2k80** [comment] 2019-05-07 16:27
or is this a a part of lamedb? which version should i use? v4 or v5?

**Comment by phunkyfish** [comment] 2019-05-07 16:31
I'm not sure what lamedb is? 

I get the OpenWebIf ipk from here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/gh-pages

**Comment by M2k80** [comment] 2019-05-07 16:34
lamedb and bouquet files both together are the channellist on enigma2. i think lamedb has stored all channels that exists

**Comment by M2k80** [comment] 2019-05-07 16:40
ok i just tried dreambox edit, and load there my channel list....it shows the same channel numbers like on my vu+
i will test to write them with dreambox edit, and look if something has changed on the webif, if not, i will try your latest build

**Comment by M2k80** [comment] 2019-05-07 16:45
funny is, on the webif, when i open the integrated bouquet editor, channel numbers are correct, too

**Comment by M2k80** [comment] 2019-05-07 16:54
ok i think i found the problem.
on the vu+ i found in the settings something that is called "alternative counting methods" (i translated it to english, so idk if its realy the same wordings on openvix)
if it is disabled my local channel list shows like on my screenshot, sky hd bouquet has 68,69,70 as channel number.
if it is enabled, every bouquet begin with 1,2,3,4.

so the question is now, why does the webif api use the alternative counting methods enabled, when my vu+ has it disabled - so its an webif bug, right?

**Comment by phunkyfish** [comment] 2019-05-07 17:11
It must be an OpenWebIf bug so, although you might get corrected on that by the author!

There was another user and all they did was switch to ABM without changing OpenWebIf version and it all started to work. So it may not be OpenWebIf.

**Comment by M2k80** [comment] 2019-05-07 17:14
just updated to the version from your link,  problem still exists.
i am just wondering why its working for you and not working for me, we both use openvix and now latest webif version. hmm..

**Comment by phunkyfish** [comment] 2019-05-07 17:18
Try ABM. If it works you should be able to figure out what’s different in the channe files.

**Comment by M2k80** [comment] 2019-05-07 17:20
if you would use http://your-ip/api/getallservices all numbers are correct and bouquet names are listed too

**Comment by M2k80** [comment] 2019-05-07 17:22
my output of getallservices https://paste.kodi.tv/irirevaboz

**Comment by phunkyfish** [comment] 2019-05-07 17:43
So it’s only the getservices call that’s wrong? That’s definitely an OpenWebIf bug so. 

It’s better to open an issue with OpenWebIf and get it fixed. The addon works by bouquet. Many users only load a single bouquet on very old STBs and this change would not work well for them.

In addition I would need to call both the old and new apis to support provider and picon url too.

**Comment by M2k80** [comment] 2019-05-07 18:10
my english is not so well, you have both getservices and getallservices from me, could you maybe please open the issue, i think you can explain it better than me?

but i am still wondering why its working for you and not me xD

**Comment by phunkyfish** [comment] 2019-05-07 18:37
Me too. Let me do a few more tests before I open the issue. 

I think the reason it works for getallservices is that it passes the pos value from one bouquet to the next. Calling it separately using get services passes 0 in each time, so resetting the value.

**Comment by phunkyfish** [comment] 2019-05-07 18:38
Did you try running ABM as a test? Would be good to try that before opening an issue as that is the only difference between your setup and mine.

**Comment by M2k80** [comment] 2019-05-07 18:45
does it work with my cable network?

what should i choose for local area selection? there are only uk locations. i live in germany

**Comment by phunkyfish** [comment] 2019-05-07 18:52
ABM works everywhere as far as I know, in fact someone I know from Germany uses it on cable so it must work.

**Comment by M2k80** [comment] 2019-05-07 18:54
its just downloading 28.2E bouquet.
it seems it work only for satelite

**Comment by phunkyfish** [comment] 2019-05-07 18:56
Let me ask my friend. But see does it work for 28.2

**Comment by M2k80** [comment] 2019-05-07 18:58
its just confusing, maybe i have the wrong tool installed? i am not sure...
is it on the openvix feed or do i need it install manually?

**Comment by phunkyfish** [comment] 2019-05-07 18:58
You want autobouquetsmaker and not autobouquets (28.2)

**Comment by M2k80** [comment] 2019-05-07 18:58
its not on my list

**Comment by M2k80** [comment] 2019-05-07 19:03
ok i got it by manual installation
try it now

**Comment by M2k80** [comment] 2019-05-07 19:07
ok, its not realy working, because i have to set a provider, and there is none for my country :(

**Comment by phunkyfish** [comment] 2019-05-07 19:22
Sorry, he has cable but it’s Netherlands which is supported.

**Comment by phunkyfish** [comment] 2019-05-07 20:05
So, as it happens it works for me as my first bouquet starts with channel 1 and for every bouquet OpenWebIf assumes it starts with channel 1.

As this is my master bouquet (it contains all the channels) it works for me. But all my other bouquets would be incorrect but as the channel numbers are discarded it doesn’t cause an issue.

**Comment by phunkyfish** [comment] 2019-05-07 20:05
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/938

**Comment by M2k80** [comment] 2019-05-07 20:07
thank you!

**Comment by phunkyfish** [comment] 2019-05-13 09:00
Should be fixed in #225 #226

**Comment by dellas60** [comment] 2019-05-16 09:15
the problem is always bind to the channels which is in several groups, this channels are the responsible for disorder.

**Comment by phunkyfish** [comment] 2019-05-16 11:53
Correct, as the addon only loads one instance of each channel only the first channel number will be used. To change this would be a large performance hit for users with older STBs.

So channel numbering on the STB should follow either of these guidelines:

1. Use a master bouquet as the first bouqet. Every channel is in this bouquet and it defines the numbering.
2. Each channel only appears in one bouquet.

**Comment by phunkyfish** [comment] 2019-05-21 09:40
Closing

**Closed as completed by phunkyfish** 2019-05-21 09:40 UTC
Labels: bug
