### ISSUE TITLE
Records: Folders are missing

### ISSUE THREAD

**Issue by AnTri** [kodi-pvr/pvr.vuplus#329] opened 2021-02-22 13:12 UTC
When I open the recording list, the existing folders and subfolders are not displayed.

**Comment by phunkyfish** [comment] 2021-02-22 14:47
They will only be grouped by showname. The folder structure on your device won’t be replicated.

**Comment by AnTri** [comment] 2021-02-22 15:00
my recordings are stored in different folders. How can I access my recording in subfolder?

When I enable recursive records in the settings, I get a very huge list which is not very comfortable...

**Comment by phunkyfish** [comment] 2021-02-22 16:07
Can you share some screenshots of what it looks like?

**Comment by AnTri** [comment] 2021-02-22 17:01
**PVR/TV Screenshot:**
![image](https://user-images.githubusercontent.com/6997604/108741463-102d7e00-7537-11eb-9c4e-0b5ae173dd61.png)



**Openwebif:**
![image](https://user-images.githubusercontent.com/6997604/108741740-4f5bcf00-7537-11eb-8e38-2d6ce3d463a9.png)



**Kodi (only virtual folders are shown...)**
![image](https://user-images.githubusercontent.com/6997604/108742071-a19cf000-7537-11eb-858c-63f09a884ef6.png)

![image](https://user-images.githubusercontent.com/6997604/108742242-cee99e00-7537-11eb-9878-b711c9c5e1c6.png)

**Comment by phunkyfish** [comment] 2021-02-22 18:10
I'm afraid the add-on only supports virtual folders currently. There is no support for custom directory structures I'm afraid.

**Comment by phunkyfish** [comment] 2021-02-23 09:14
Actually I think it may support folders. I just could not see it as my device does not have any folders.

Did you try enabling both folders and/or recursive in the add-on settings?

**Comment by AnTri** [comment] 2021-02-23 16:59
Hi,

enabling folder makes no differenz. I tried to set foldername. Then my hdd and movie folder are shown, but no subdirs (behind movie).
![image](https://user-images.githubusercontent.com/6997604/108878398-84802400-7600-11eb-97bd-b37a3475d8d2.png)

![image](https://user-images.githubusercontent.com/6997604/108878652-c4470b80-7600-11eb-805e-aa4df7c70b05.png)

**Comment by phunkyfish** [comment] 2021-02-23 19:55
I found one bug in the add-on but also an issue in OpenWebIf. So you will
need version 1.4.4 of openwebif to fix this. But you use the VTI image
which is stuck on version 1.2.8.

However many levels deep are your folders?

**Comment by AnTri** [comment] 2021-02-23 20:10
I installed 1.4.4 on my box...

Normally I have 3 or maximum 4 levels

Level 1: Movie (default)
Level 2: Foldername (Moviename)
Level 3: season (e.g. 01)

**Comment by phunkyfish** [comment] 2021-02-23 20:19
Ok, now you need to install the latest build of the add-on too. You can find testbuilds here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-330/1/artifacts

Then turn on keep folders and recursive in add-on settings and it should work.

**Comment by AnTri** [comment] 2021-02-23 20:27
Ok, I try to Update. What are the correct settings in the add-on?

**Comment by phunkyfish** [comment] 2021-02-23 20:32
![F489E5BD-EE97-4489-B082-B3BA85F34B81](https://user-images.githubusercontent.com/4601187/108904251-2d854980-7616-11eb-9283-d31c6eb01d02.jpeg)

**Comment by AnTri** [comment] 2021-02-23 21:29
It works great now!!!

Thanks for your quick help!

**Comment by phunkyfish** [comment] 2021-02-23 21:46
It won’t be exactly like this when finished and released but should be similar.

Once it’s finished I’ll ask you to test a new version.

**Comment by phunkyfish** [comment] 2021-02-23 23:18
Please try this version: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vuplus/detail/PR-330/4/artifacts

PR here: https://github.com/kodi-pvr/pvr.vuplus/pull/330

It splits the setting group recordings by title and keep folder structure so they can both be used together.

**Comment by AnTri** [comment] 2021-02-24 22:17
I have tested the version. the list of recordings looks good now. However, the loading time at startup is significantly longer.

But what I noticed: After about 30min the add-on crashes and Kodi is completely terminated.

![image](https://user-images.githubusercontent.com/6997604/109073308-7e6c6f00-76f6-11eb-8e8f-006b1f15e234.png)

**Comment by phunkyfish** [comment] 2021-02-24 23:22
Was the loading time ok with the previous version? I.e. the first testbuild I gave you.

**Comment by phunkyfish** [comment] 2021-02-25 18:27
I was not able to reproduce this. The crash or the startup delay.

Can you try clearing all PVR data and try again?

**Comment by AnTri** [comment] 2021-02-25 18:57
Hello, I have now tried it on a second device. The first start of the add-on took about 30s (stuck at 75%). The second start was very fast. The add-on no longer crashes.I will keep on trying. 

How can I clear all PVR data?

Thanks for your help

**Comment by phunkyfish** [comment] 2021-02-25 20:11
In kodi settings go to PVR and live tv and there should be an option in the first tab.

**Comment by phunkyfish** [comment] 2021-02-25 22:04
This just be that how the EPG is stored was changed in kodi 19. Previously it was in memory whereas now it’s stored on disk.

It could be that the delay the first time is it saving all the data.

**Comment by phunkyfish** [comment] 2022-04-20 12:00
Closing as the problem was fixed.

**Closed as completed by phunkyfish** 2022-04-20 12:00 UTC
