### ISSUE TITLE
Addon does not work, with single bouquet option 

### ISSUE THREAD

**Issue by sidey79** [kodi-pvr/pvr.vuplus#97] opened 2018-09-29 19:00 UTC
I'm using CoreElec 8.95.2.

 Since the update to 3.10.02 (today) i get alwas an error 

`20:49:16.584 T:3990016880   ERROR: Process error processing job pvr-startup`

when only one Bouqet should be loaded. The module doesn't work at all in that situation.

If i disable this option, the module loads and i can use it.

**Comment by phunkyfish** [comment] 2018-09-29 20:44
This should be fixed in 3.11.3. There is a PR in for it now.

Can you also post the rest of your debug log so I can confirm?

That one line could be caused by a number of issues.

**Comment by phunkyfish** [comment] 2018-09-29 23:12
Yes, that would be a good start.

Thanks ;)

**Comment by sidey79** [comment] 2018-09-30 12:49
okay here is the debug log, with enabled only one bouqet :

```
14:43:53.308 T:3680527216   DEBUG: CWebServer[8080]: request received for /jsonrpc?JSONRPC.Ping
14:43:53.326 T:3680527216   DEBUG: CWebServer[8080]: request received for /jsonrpc?Application.GetProperties
14:43:53.342 T:3680527216   DEBUG: CWebServer[8080]: request received for /jsonrpc?Player.GetActivePlayers
14:43:54.835 T:3820938096   DEBUG: PushCecKeypress - received key  b duration 0
14:43:54.848 T:4095324176   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
14:43:54.872 T:4095324176   DEBUG: CAddonMgr: enabled pvr.vuplus
14:43:54.872 T:3986678640   DEBUG: CBinaryAddonManager::EnableEvent: Enable addon 'pvr.vuplus' on binary addon manager
14:43:54.883 T:3978285936   DEBUG: Create: Creating PVR add-on instance 'VU+ / Enigma2 Client'
14:43:54.883 T:3978285936   DEBUG: ADDON: Dll Initializing - VU+ / Enigma2 Client
14:43:54.884 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: ADDON_Create - Creating VU+ PVR-Client
14:43:54.884 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'host'
14:43:54.885 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.885 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.886 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.886 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'user'
14:43:54.887 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.887 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.889 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.889 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'recordingpath'
14:43:54.890 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.890 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.892 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.893 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'pass'
14:43:54.894 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.894 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.895 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.895 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'use_secure'
14:43:54.896 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.896 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.898 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.898 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'autoconfig'
14:43:54.899 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.899 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.900 T:4095324176   DEBUG: CGUIMediaWindow::GetDirectory (addons://user/xbmc.pvrclient)
14:43:54.900 T:4095324176   DEBUG:   ParentPath = [addons://user/xbmc.pvrclient]
14:43:54.901 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.901 T:3696218992   DEBUG: Thread waiting start, auto delete: false
14:43:54.901 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'streamport'
14:43:54.902 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.902 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.903 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.904 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'webport'
14:43:54.904 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.904 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.906 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.906 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'onlinepicons'
14:43:54.907 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.907 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.908 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.909 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'onlycurrent'
14:43:54.910 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.910 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.911 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.911 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'setpowerstate'
14:43:54.912 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.912 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.913 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.914 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'keepfolders'
14:43:54.915 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.915 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.916 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.916 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'zap'
14:43:54.917 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.917 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.918 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.919 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'onlyonegroup'
14:43:54.920 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.920 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.921 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.921 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'onegroup'
14:43:54.922 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.922 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.923 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.924 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'timerlistcleanup'
14:43:54.924 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.924 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.926 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.926 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'updateint'
14:43:54.927 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.927 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.928 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.928 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'iconpath'
14:43:54.929 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.929 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.931 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.931 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'enabletimeshift'
14:43:54.932 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.932 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.933 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.933 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'timeshiftbufferpath'
14:43:54.935 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.935 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.936 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.936 T:3978285936   DEBUG: CAddonCallbacksAddon - GetAddonSetting - add-on 'VU+ / Enigma2 Client' requests setting 'readtimeout'
14:43:54.937 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting definitions
14:43:54.937 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: trying to load setting definitions from old format...
14:43:54.939 T:3978285936   DEBUG: CAddonSettings[pvr.vuplus]: loading setting values
14:43:54.940 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - VU+ Addon Configuration options
14:43:54.940 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - Hostname: 'et9x00'
14:43:54.940 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - WebPort: '80'
14:43:54.940 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open - StreamPort: '8001'
14:43:54.940 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: Open Use HTTPS: 'false'
14:43:54.940 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/deviceinfo'
14:43:54.940 T:3978285936   DEBUG: CFileCache::Open - opening <web/deviceinfo> using cache
14:43:54.940 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/deviceinfo
14:43:54.941 T:3978285936    INFO: easy_acquire - Created session to http://et9x00
14:43:54.954 T:3696218992   DEBUG: CAddonMgr::GetAvailableUpdates took 37 ms
14:43:54.956 T:3696218992   DEBUG: Thread waiting 3696218992 terminating
14:43:54.960 T:3696218992   DEBUG: Thread BackgroundLoader start, auto delete: false
14:43:54.962 T:3696218992   DEBUG: Thread BackgroundLoader 3696218992 terminating
14:43:55.073 T:3820938096   DEBUG: PushCecKeypress - received key  b duration 238
14:43:55.298 T:3829330800   DEBUG: Thread FileCache start, auto delete: false
14:43:55.299 T:3829330800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:55.349 T:3829330800   DEBUG: Thread FileCache 3829330800 terminating
14:43:55.349 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 1253
14:43:55.349 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo - DeviceInfo
14:43:55.349 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo - E2EnigmaVersion: 2017-10-15
14:43:55.349 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo - E2ImageVersion: 6.0.0
14:43:55.349 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo - E2WebIfVersion: OWIF 1.2.7
14:43:55.349 T:3978285936  NOTICE: AddOnLog: VU+ / Enigma2 Client: GetDeviceInfo - E2DeviceName: ET9200
14:43:55.349 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/getlocations'
14:43:55.350 T:3978285936   DEBUG: CFileCache::Open - opening <web/getlocations> using cache
14:43:55.350 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/getlocations
14:43:55.436 T:3829330800   DEBUG: Thread FileCache start, auto delete: false
14:43:55.436 T:3829330800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:55.486 T:3829330800   DEBUG: Thread FileCache 3829330800 terminating
14:43:55.486 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 112
14:43:55.486 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadLocations Added '/media/hdd/movie/' as a recording location
14:43:55.487 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadLocations Loded '1' recording locations
14:43:55.487 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/getservices'
14:43:55.487 T:3978285936   DEBUG: CFileCache::Open - opening <web/getservices> using cache
14:43:55.487 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/getservices
14:43:55.618 T:3829330800   DEBUG: Thread FileCache start, auto delete: false
14:43:55.619 T:3829330800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:55.619 T:3829330800   DEBUG: Thread FileCache 3829330800 terminating
14:43:55.619 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 4403
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Only one group is set, but current e2servicename 'Favourites (TV)' does not match requested name 'Kodi (TV)'
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Only one group is set, but current e2servicename '3D' does not match requested name 'Kodi (TV)'
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Only one group is set, but current e2servicename 'Mein TV' does not match requested name 'Kodi (TV)'
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Only one group is set, but current e2servicename 'kids' does not match requested name 'Kodi (TV)'
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Only one group is set, but current e2servicename 'Last Scanned' does not match requested name 'Kodi (TV)'
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Loaded channelgroup: Kodi (TV)
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannelGroups Loaded 1 Channelsgroups
14:43:55.620 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels loading channel group: 'Kodi (TV)'
14:43:55.621 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/getservices?sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Ekodi%5F%5Ftv%5F%2Etv%22%20ORDER%20BY%20bouquet'
14:43:55.621 T:3978285936   DEBUG: CFileCache::Open - opening <web/getservices> using cache
14:43:55.621 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/getservices?sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Ekodi%5F%5Ftv%5F%2Etv%22%20ORDER%20BY%20bouquet
14:43:55.720 T:3829330800   DEBUG: Thread FileCache start, auto delete: false
14:43:55.720 T:3829330800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:55.770 T:3829330800   DEBUG: Thread FileCache 3829330800 terminating
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 1356
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: Das Erste HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_283D_3FB_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: ZDF HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_2B66_3F3_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: RTL HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_EF10_421_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: SAT.1 HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: N24 DOKU, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_1_30_5_85_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: KiKA HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_2B98_3F2_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded channel: n-tv HD, Icon: http://xxxx:xxxx@et9x00:80/picon/1_0_19_EF14_421_1_C00000_0_0_0.png
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels Loaded 7 Channels
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadChannels loading channel group: 'radio'
14:43:55.771 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/getservices?sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Efavourites%2Eradio%22%20ORDER%20BY%20bouquet'
14:43:55.772 T:3978285936   DEBUG: CFileCache::Open - opening <web/getservices> using cache
14:43:55.772 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/getservices?sRef=1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet%2Efavourites%2Eradio%22%20ORDER%20BY%20bouquet
14:43:55.861 T:3829330800   DEBUG: Thread FileCache start, auto delete: false
14:43:55.861 T:3829330800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:55.911 T:3829330800   DEBUG: Thread FileCache 3829330800 terminating
14:43:55.911 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 72
14:43:55.911 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: Could not find <e2service> element
14:43:55.911 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Open webAPI with URL: 'http://xxxx:xxxx@et9x00:80/web/timerlist'
14:43:55.912 T:3978285936   DEBUG: CFileCache::Open - opening <web/timerlist> using cache
14:43:55.912 T:3978285936   DEBUG: CurlFile::Open(0x21c1590) http://et9x00:80/web/timerlist
14:43:56.728 T:4027573104   DEBUG: Thread FileCache start, auto delete: false
14:43:56.750 T:4027573104    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
14:43:56.750 T:4027573104   DEBUG: Thread FileCache 4027573104 terminating
14:43:56.750 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: GetHttpXML Got result. Length: 100306
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers Processing timer 'Formel 1: Das Rennen'
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers e2state is: 2
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers Timer state is: RECORDING
14:43:56.764 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadTimers fetched Timer entry 'Formel 1: Das Rennen', begin '1538304300', end '1538313000'
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers Processing timer 'Formel 1: Siegerehrung und Highlights'
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers e2state is: 2
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers Timer state is: RECORDING
14:43:56.764 T:3978285936    INFO: AddOnLog: VU+ / Enigma2 Client: LoadTimers fetched Timer entry 'Formel 1: Siegerehrung und Highlights', begin '1538311200', end '1538315100'
14:43:56.764 T:3978285936   DEBUG: AddOnLog: VU+ / Enigma2 Client: LoadTimers Processing timer 'Yukon Men - Überleben in Alaska'
14:43:56.767 T:3978285936   ERROR: Process error processing job pvr-update-addons
```

I hope this helps.

**Comment by sidey79** [comment] 2018-09-30 18:58
I'm using OpenATV 6.0.0 as distro with OWIF 1.2.7

There are serval timers with that name, nor sure which one it was. Here is the topmost from the output:
```
<e2timer>
<e2servicereference>1:0:19:82:6:85:C00000:0:0:0:</e2servicereference>
<e2servicename>Discovery HD</e2servicename>
<e2eit>39173</e2eit>
<e2name>Yukon Men - Überleben in Alaska</e2name>
<e2description>Am seidenen Faden</e2description>
<e2descriptionextended>
4. Staffel, Folge 6: Mehr Menschen und weniger wilde Tiere: Stan Zuray ist nicht begeistert vom Bau der neuen Straße, die Tanana mit dem regionalen Verkehrsnetz verbindet. Denn möglicherweise herrscht in der kleinen Ortschaft bald mehr Trubel, als den Bewohnern lieb ist. Deshalb überlegt der Aussteiger, ob er wieder in seine alte Jagdhütte am Tozi River ziehen soll. Dort könnte er ungestört jagen, fischen und Hunde züchten. Die Moores müssen sich derweil beim "Yukon River Open" beweisen, dem wichtigsten Schlittenrennen des Jahres. 44 Min. USA 2015. Ab 12 Jahren
</e2descriptionextended>
<e2disabled>0</e2disabled>
<e2timebegin>1538371320</e2timebegin>
<e2timeend>1538374500</e2timeend>
<e2duration>3180</e2duration>
<e2startprepare>1538371300</e2startprepare>
<e2justplay>0</e2justplay>
<e2afterevent>3</e2afterevent>
<e2location>None</e2location>
<e2tags/>
<e2logentries>
[(1538191188, 500, '[AutoTimer] Try to add new timer based on AutoTimer Yukon Men - \xc3\x9cberleben in Alaska.'), (1538191188, 509, '[AutoTimer] Timer start on: Mon Oct 1 07:22:00 2018')]
</e2logentries>
<e2filename>
/media/hdd/movie/20181001 0722 - Discovery HD - Yukon Men - Überleben in Alaska
</e2filename>
<e2backoff>0</e2backoff>
<e2nextactivation/>
<e2firsttryprepare>0</e2firsttryprepare>
<e2state>0</e2state>
<e2repeated>0</e2repeated>
<e2dontsave>0</e2dontsave>
<e2cancled>False</e2cancled>
<e2toggledisabled>1</e2toggledisabled>
<e2toggledisabledimg>off</e2toggledisabledimg>
<e2alwayszap>0</e2alwayszap>
</e2timer>
```

**Comment by phunkyfish** [comment] 2018-09-30 19:52
That’s perfect. The fix is to exclude timers that use channels that are in not in the one bouquet you have chosen.

On my STB the only bouquet has all the channels so I never see this issue 😉

**Comment by phunkyfish** [comment] 2018-09-30 19:53
Also,

OpenWebIf 1.3.x is needed to use auto timers feature.

I can try to support 1.2.x but would need your help to get the right config.

**Comment by sidey79** [comment] 2018-09-30 20:08
I think i can update my receiver to a recent version or do you think many people are using webif 1.2.x ?

**Comment by phunkyfish** [comment] 2018-09-30 20:59
On that I’m not sure. I also don’t know how big a difference there is in the APIs.

If you can upgrade I’d say do so. I know 1.3.x is available for Openvix but I don’t know about the other distros.

If you can upgrade I will just assume anyone else can 😉

**Comment by sidey79** [comment] 2018-09-30 21:00
I think i can. My Image is very old, and newer versions are available.

**Comment by phunkyfish** [comment] 2018-10-01 06:36
For the fix required for this issue you will need version 3.11.3 of the addon. Hopefully the PR containing it will get merged today.

**Comment by phunkyfish** [comment] 2018-10-04 10:49
Fixed in: https://github.com/kodi-pvr/pvr.vuplus/pull/96

**Closed** 2018-10-04 10:49 UTC
Labels: bug
